services:
  SportClimbing\IfscCalendar\Application\Command\BuildCommand:
    class: SportClimbing\IfscCalendar\Application\Command\BuildCommand
    public: true
    tags: [ console.command ]
    lazy: true
    arguments:
      - '@SportClimbing\IfscCalendar\Application\UseCase\BuildCalendar\BuildCalendarUseCase'

  SportClimbing\IfscCalendar\Application\UseCase\BuildCalendar\BuildCalendarUseCase:
    class: SportClimbing\IfscCalendar\Application\UseCase\BuildCalendar\BuildCalendarUseCase
    autowire: true
    public: true
