services:
  # Calendar
  SportClimbing\IfscCalendar\Domain\Calendar\IFSCCalendarBuilderFactory:
    class: SportClimbing\IfscCalendar\Domain\Calendar\IFSCCalendarBuilderFactory
    arguments:
      - '@SportClimbing\IfscCalendar\Infrastructure\Calendar\ICalCalendar'
      - '@SportClimbing\IfscCalendar\Infrastructure\Calendar\JsonCalendar'

  SportClimbing\IfscCalendar\Domain\Calendar\IFSCCalendarBuilder:
    class: SportClimbing\IfscCalendar\Domain\Calendar\IFSCCalendarBuilder
    arguments:
      - '@SportClimbing\IfscCalendar\Domain\Calendar\IFSCCalendarBuilderFactory'
      - '@SportClimbing\IfscCalendar\Domain\Event\IFSCEventsFetcher'
      - '@SportClimbing\IfscCalendar\Domain\Calendar\IFSCCalendarPostProcess'

  SportClimbing\IfscCalendar\Domain\Calendar\IFSCCalendarPostProcess:
    class: SportClimbing\IfscCalendar\Domain\Calendar\IFSCCalendarPostProcess
    arguments:
      - '@SportClimbing\IfscCalendar\Domain\Event\IFSCEventSorter'
      - '@SportClimbing\IfscCalendar\Domain\Calendar\PostProcess\Season2026PostProcessor'

  SportClimbing\IfscCalendar\Domain\Calendar\PostProcess\Season2026PostProcessor:
    class: SportClimbing\IfscCalendar\Domain\Calendar\PostProcess\Season2026PostProcessor
    arguments:
      - '@SportClimbing\IfscCalendar\Domain\Round\IFSCRoundFactory'
      - '@SportClimbing\IfscCalendar\Domain\Schedule\IFSCScheduleFactory'

  SportClimbing\IfscCalendar\Domain\Calendar\SiteURLBuilder:
    class: SportClimbing\IfscCalendar\Domain\Calendar\SiteURLBuilder
    arguments:
      - '%site_event_url%'

  # Ranking
  SportClimbing\IfscCalendar\Domain\Ranking\IFSCAthleteRankingCalculator: ~

  # Start List
  SportClimbing\IfscCalendar\Domain\StartList\IFSCStartListGenerator:
    class: SportClimbing\IfscCalendar\Domain\StartList\IFSCStartListGenerator
    arguments:
      - '@SportClimbing\IfscCalendar\Infrastructure\StartList\ApiStartListProvider'
      - '@SportClimbing\IfscCalendar\Domain\Athlete\IFSCAthleteService'
      - '@SportClimbing\IfscCalendar\Domain\Ranking\IFSCAthleteRankingCalculator'

  # Athlete
  SportClimbing\IfscCalendar\Domain\Athlete\IFSCAthleteService:
    class: SportClimbing\IfscCalendar\Domain\Athlete\IFSCAthleteService
    arguments:
      - '@SportClimbing\IfscCalendar\Infrastructure\Athlete\CachedAthleteProvider'

  # YouTube
  SportClimbing\IfscCalendar\Domain\YouTube\YouTubeVideoProvider:
    class: SportClimbing\IfscCalendar\Domain\YouTube\YouTubeVideoProvider
    arguments:
      - '@SportClimbing\IfscCalendar\Infrastructure\YouTube\YouTubeVideoProvider'

  SportClimbing\IfscCalendar\Domain\YouTube\YouTubeLinkMatcher:
    class: SportClimbing\IfscCalendar\Domain\YouTube\YouTubeLinkMatcher
    autowire: true

  SportClimbing\IfscCalendar\Domain\YouTube\YouTubeLiveStreamFinderFactory:
    class: SportClimbing\IfscCalendar\Domain\YouTube\YouTubeLiveStreamFinderFactory
    arguments:
      - '@SportClimbing\IfscCalendar\Domain\YouTube\YouTubeLinkMatcher'
      - '@SportClimbing\IfscCalendar\Domain\YouTube\YouTubeVideoProvider'

  SportClimbing\IfscCalendar\Domain\YouTube\YouTubeLiveStreamFinder:
    factory: [ '@SportClimbing\IfscCalendar\Domain\YouTube\YouTubeLiveStreamFinderFactory', 'create']

  # Schedule
  SportClimbing\IfscCalendar\Domain\Schedule\IFSCScheduleFactory:
    class: SportClimbing\IfscCalendar\Domain\Schedule\IFSCScheduleFactory
    arguments:
      - '@SportClimbing\IfscCalendar\Domain\Tags\IFSCTagsParser'
      - '@SportClimbing\IfscCalendar\Domain\Round\IFSCRoundNameNormalizer'

  # Events
  SportClimbing\IfscCalendar\Domain\Event\IFSCEventsFetcher:
    class: SportClimbing\IfscCalendar\Domain\Event\IFSCEventsFetcher
    arguments:
      - '@SportClimbing\IfscCalendar\Domain\Event\IFSCEventFactory'
      - '@SportClimbing\IfscCalendar\Domain\Round\IFSCRoundFactory'
      - '@SportClimbing\IfscCalendar\Domain\Schedule\IFSCScheduleFactory'
      - '@SportClimbing\IfscCalendar\Infrastructure\DomainEvent\SymfonyEventDispatcher'
      - '@SportClimbing\IfscCalendar\Domain\Event\IFSCEventSlug'

  SportClimbing\IfscCalendar\Domain\Event\IFSCEventFactory:
    class: SportClimbing\IfscCalendar\Domain\Event\IFSCEventFactory
    arguments:
      - '@SportClimbing\IfscCalendar\Domain\Calendar\SiteURLBuilder'
      - '@SportClimbing\IfscCalendar\Domain\StartList\IFSCStartListGenerator'

  SportClimbing\IfscCalendar\Domain\Event\IFSCEventSlug: ~
  SportClimbing\IfscCalendar\Domain\Event\IFSCEventSorter: ~

  # Round
  SportClimbing\IfscCalendar\Domain\Round\IFSCAverageRoundDuration:
    class: SportClimbing\IfscCalendar\Domain\Round\IFSCAverageRoundDuration
    arguments:
      - '@SportClimbing\IfscCalendar\Domain\Round\IFSCAverageRoundDurationLookupKey'

  SportClimbing\IfscCalendar\Domain\Round\IFSCAverageRoundDurationLookupKey: ~

  SportClimbing\IfscCalendar\Domain\Round\IFSCRoundFactory:
    class: SportClimbing\IfscCalendar\Domain\Round\IFSCRoundFactory
    arguments:
      - '@SportClimbing\IfscCalendar\Domain\Tags\IFSCTagsParser'
      - '@SportClimbing\IfscCalendar\Domain\YouTube\YouTubeLiveStreamFinder'
      - '@SportClimbing\IfscCalendar\Domain\Round\IFSCAverageRoundDuration'

  SportClimbing\IfscCalendar\Domain\Round\IFSCRoundNameNormalizer:
    class: SportClimbing\IfscCalendar\Domain\Round\IFSCRoundNameNormalizer
    arguments:
      - '@SportClimbing\IfscCalendar\Domain\Tags\IFSCTagsParser'

  # Tags
  SportClimbing\IfscCalendar\Domain\Tags\IFSCTagsParser: ~
