name: "Build & Push Docker image"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@master

      - name: "Build and publish a Docker image for ${{ github.repository }}"
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}
          github_token: ${{ secrets.GH_PACKAGES_TOKEN }}
          docker_io_token: ${{ secrets.DOCKER_IO_ACCESS_TOKEN }}
          docker_io_user: sportclimbing
          extra_args: --no-cache

      - name: "Update calendar"
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'sportclimbing',
              repo: 'ifsc-calendar',
              workflow_id: 'update-calendar.yml',
              ref: 'main'
            })
